parameters:
#    netgen_hybrid_approach.example.class: Netgen\HybridApproachBundle\Example

services:
    netgen_search_and_filter.location_75:
            class: Netgen\SearchAndFilterBundle\Components\SearchAdapter
            arguments:
                - @netgen_hybrid_approach.handler.legacy
                - @netgen_hybrid_approach.form_type.filter_search_form_type
                - @form.factory
                - @netgen_hybrid_approach.criteria_builder.legacy_list_filter
                - @netgen_hybrid_approach.result_converter.legacy
                - NetgenHybridApproachBundle:Default:filter_results.html.twig
                - NetgenHybridApproachBundle:forms:embedded_form.html.twig
                - %netgen_search_and_filter.page_limit%

    netgen_hybrid_approach.handler.legacy:
            class: Netgen\HybridApproachBundle\Components\SearchHandler\LegacyListHandler
            arguments:
                - @ezpublish_legacy.kernel
                - @ezpublish.api.repository

    netgen_hybrid_approach.form_type.filter_search_form_type:
        class: Netgen\HybridApproachBundle\Form\Type\FilterSearchType

    netgen_hybrid_approach.criteria_builder.legacy_list_filter:
        class: Netgen\HybridApproachBundle\Components\SearchCriteriaBuilder\LegacyFilterCriteriaBuilder

    netgen_hybrid_approach.result_converter.legacy:
        class: Netgen\HybridApproachBundle\Components\SearchResultConverter\LegacyFilterResultConverter
        arguments:
            - @ezpublish.api.repository




